### ISSUE TITLE
order of models

### ISSUE THREAD

**Issue by andreashlarsen** [ehb54/GenApp-Shape2SAS#1]
bug description: 

if the first row for model 2 is left as "choose model" and the second row is used, fx "sphere", then you get an error: 

```
Unexpected results:

error => Empty JSON returned from executable

error_output => Traceback (most recent call last): File "/share/apps/genapp/mcsim/bin/mcsim.py", line 169, in N,rho,N_exclude,volume,x_new,y_new,z_new,p_new = gen_all_points(Number_of_objects,x,y,z,model,a,b,c,p,exclude_overlap) File "/state/partition1/apps/genapp/mcsim/bin/helpfunctions.py", line 291, in gen_all_points x_add,y_add,z_add,p_add,N_x = check_overlap(x_add,y_add,z_add,p_add,x_com[j],y_com[j],z_com[j],model[j],a[j],b[j],c[j]) File "/state/partition1/apps/genapp/mcsim/bin/helpfunctions.py", line 399, in check_overlap N_x = len(x)-len(idx[0]) IndexError: list index out of range
```
likely because the order matters, and it ruins something that the first row is not a model, but "choose model", whereas the next is a model.

**Comment by andreashlarsen** [comment]
solved - bugfix will be updated asap
